### ISSUE TITLE
try to build libkafka: codeblocks/tdm-gcc/windows10 but boost_root - cmake problem

### ISSUE THREAD

**Issue by meir100** [danieljoos/libkafka-asio#26]
try to build libkafka with codeblocks /cmake/tdm-gcc/windows10, but cmake cannot find: boost_root
even if it is declared %boost_root% and in the path.
in cmake i defined location of: boost.

CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: C:/boost_1_67_0_GCC

  Could not find the following Boost libraries:

          boost_thread
          boost_system

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  examples/cpp03/CMakeLists.txt:6 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: C:/boost_1_67_0_GCC

  Could not find the following Boost libraries:

          boost_thread
          boost_system

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  examples/cpp11/CMakeLists.txt:6 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindGTest.cmake:196 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  test/CMakeLists.txt:6 (find_package)

Configuring incomplete, errors occurred!
See also "C:/libkafka-asio/build/CMakeFiles/CMakeOutput.log".

**Comment by danieljoos** [comment]
Hi there. It seems that you haven't installed/configured the Boost library with CMake correctly.

You also don't need to build something with CMake if you don't want to. The included `CMakeLists` are used to build the tests and the examples.
To use the library for your project, it is enough to specify the `lib` directory as additional include directory. The only thing you need is `boost` (and optionally `zlib` and/or `libsnappy`).
