### ISSUE TITLE
missing feature: ability to send a correlation_id

### ISSUE THREAD

**Issue by DEvil0000** [danieljoos/libkafka-asio#3]
with the current API i don't see a way to send a correlation_id on produce.

**Comment by danieljoos** [comment]
There is a mutator `set_correlation_id` available on every request class. It is defined on the base `request` class in `request.h`.
This is missing in the documentation. I will add this!

**Comment by DEvil0000** [comment]
oh yes thanks - but it looks like I can not get it.
when I call `response->correlation_id()` on the produce response I get segfault:
```
/development/Lib/boost-1.58.0/boost/optional/optional.hpp:1014: boost::optional<T>::pointer_const_type boost::optional<T>::operator->() const [with T = libkafka_asio::ProduceResponse, boost::optional<T>::pointer_const_type = const libkafka_asio::ProduceResponse*]: Assertion `this->is_initialized()' failed.
Aborted (core dumped)
```
