### ISSUE TITLE
The callbacks in Client do not support members

### ISSUE THREAD

**Issue by DEvil0000** [danieljoos/libkafka-asio#6]
The `Client` callbacks do not support member functions as a target.
They only support plain functions.

Expected API usage example:
```
client.AsyncRequest(metaRequest, &MyClass::HandleMetaRequest, this);
```

**Comment by danieljoos** [comment]
You could use boost::bind (or std::bind in C++11) for such a case. The Boost.Asio library does it the same way. Lambda function should also be possible using C++11. Behind the scenes, the client stores the function as boost::function object. This enables a user to either use plain functions or function objects (which can point to a member function + `this` pointer -- and possibly some more parameters)

**Comment by DEvil0000** [comment]
If I get you right you mean something like this:
```
client_.AsyncRequest(request, boost::bind(&SimpleProducer::handleRequest, this));
```
but this is also not working.
I think the underlying problem is that the pointer is from a "different" type when pointing to a member. But maybe I just try to use it incorrect.
Would you please provide an example?

**Comment by danieljoos** [comment]
You also need to specify the placeholders for the 2 parameters:
```cpp
client_->AsyncRequest(request, boost::bind(&Test2::HandleRequest, this, ::_1, ::_2));
```
Where the handler member function looks like this:
```cpp
class Test2
{
    void HandleRequest(
        const Client::ErrorCodeType& err,
        const ProduceResponse::OptionalType& response)
    {
    }
}
```

You can also store the bound member function in a function object and hand-over that object:
```cpp
using libkafka_asio::Client;
using libkafka_asio::ProduceRequest;

Client::Handler<ProduceRequest>::Type myfunc = boost::bind(&Test2::HandleRequest, this, ::_1, ::_2);
client_->AsyncRequest(request, myfunc);
```

**Comment by DEvil0000** [comment]
thanks works.
I just missed the _1 & _2 part
