### ISSUE TITLE
[Client] sending requests pretty frequent results in error "Another operation is still in progress"

### ISSUE THREAD

**Issue by DEvil0000** [danieljoos/libkafka-asio#7]
I was trying to send `MessageSets` with 1000 `Messages` at a high rate. This is why I was running into this.
It seams the `Client` return with a error in the callback because it is in `kStateWriting`. Callback triggered in `AsyncRequest`.
I would not expect a callback for this case - I would expect a return value indicating this.
Or more correct I would expect a `Client` where I can send more than one request at a time (or queue them?). I don't like to care about Client states and being busy.

Such a MessageSet takes about 10 to 20 ms until I can use the Client again. Compared to the faked rdkafak performance this is pretty slow.

I guess it is somehow `Network`/`Socket`/`Connection`/`Buffer` related.
Should it open more Connections to the Broker?

**Comment by danieljoos** [comment]
I would like to keep a single connection for each Client object. My plan is, to introduce some kind of producer implementation in future, which handles multiple connections to all leading brokers (using multiple client objects) and is able to queue messages for sending. Maybe the name `Client` is a bit misleading in this context. Think about it as a _Connection_.

**Comment by DEvil0000** [comment]
I started to implement something like a simpleProducer (have sent you a mail with the link) ;)
In this case it is a bit more work.

**Comment by DEvil0000** [comment]
I would like to add request queueing in the `Client` class  in case the `Client` is not ready to process a request now.
Is this OK for you or would you like to keep it simple and build a more "high" level client around it? In this case I would like to rename the class to `Connection`

**Comment by skarlsson** [comment]
I'm lurking in the background following all asio things.... I did something similar ie a 
client for handling line protocol, low-level producer to handle one partition and a high level producer that handles multiple lowlevel producers. It works out quite well.

Have a look and steal something (as I plan to steal your compression code...)

The library is geared to async io using one thread - think node-js, but has quite qood performance
https://github.com/bitbouncer/csi-kafka

**Comment by DEvil0000** [comment]
@skarlsson 
I was actually looking at your repository (not to deeply) before looking at this one.
I don't like the dependency to your csi build scripts with a huge amount of libs. (and even with it the setup was anoying - I think I was not even getting it to compile completely)

I like the clean protocol structure in this repo and the ability’s of your consumers/producers.
I think the code in this repo is well structured and easy to read even for non boost experienced programmers. And Mr. Joos was working a lot on compression - so it was looking more active. So I thought of just extending the code there.

Would be nice if we could merge the best of both repos.

**Comment by danieljoos** [comment]
I also had a deeper look at @skarlsson's repo. I really like the producer and consumer implementation there. Unfortunately, I required a non-C++11 implementation of the Kafka protocol, which was one of the reasons, I started this project. Really appreciate your work, @DEvil0000. Also had a look at your `SimpleProducer` implementation, which looks pretty much the way we need it.

Looking at other Kafka clients, they all do queue the messages rather than the produce requests.  The producer should also cover getting the metadata (e.g. every 10 min -- as implemented in the Java/Scala Kafka client) and managing connections to all brokers that are currently leaders for each of a Topic's partitions.

Also had a look at the performance measurements, given in librdkafka's documentation. Unfortunately, they only state how many messages per second have been sent and not how many requests. Doing some quick tests, I am able to send around 400000 messages per second (100 Byte per message; 1000 messages per request; required-acks: 0) to a single Kafka broker, running in a _boot2docker_ VM. The test-client was running on a Windows Server machine. These numbers are way worse than the ones from _librdkafka_ (around 700000). I will repeat the tests in the next days on my Linux box, where I can run a local Kafka server more easily (without having the overhead of the VM). Using the Visual Studio profiler, the identified hot-path of the test was the `WriteMessage` function, more specifically the write operation on the output stream. Maybe using another approach there (without iostreams), can also increase the performance of the library.

**Comment by danieljoos** [comment]
Some update regarding the performance of writing a lot of produce requests:
For the testing, I used this little test code, which does produce a specified amount of produce requests including 1000 messages with each of them having a value of 100 Bytes set:
https://gist.github.com/danieljoos/45e5e8c5146504d16754

I was testing it on my Linux PC (Core i7 3,4 Ghz, 16 GB RAM, pretty normal stuff) first without using any compiler optimizations and got nearly the same values as for the tests on the Windows system (see my last comment). Then I turned on compiler optimizations (basically I used `set(CMAKE_BUILD_TYPE Release)` and let CMake do it for me). Now things look a bit different:
```
Executed 1000 produce requests
Produced 1000000 messages
Took 1068623 microseconds / 1.06862s
935.784 requests per second
935784 messages per second
89.2433 MB per second
1.06862 ms per request
```

**Comment by DEvil0000** [comment]
that looks fast. But I think it is kind of cheated with `required_acks=0` - this is no real use case.

but back to topic:
1) there should really be a queue for the socket operations.
see boost example here: http://www.boost.org/doc/libs/1_58_0/doc/html/boost_asio/example/cpp03/chat/chat_client.cpp
this looks easy but the way the `request` is implemented or lets say because it is a template you can not setup a queue like this: `std::queue<TRequest> queue;` - (you need the queue to live in class context but the class is not a template class).
So I think this should be changed to some other pattern. giving the `API_KEY` as constructor parameter or using virtual functions. Is there any reason for it being a template?
What do you think about this?
2) are you fine with renaming `Client` to `Connection` and let a new client class handle multiple connections?

**Comment by danieljoos** [comment]
I used `required_acks=0` to have nearly the same test setup as _librdkafka_ did use (see _Test2_ on  https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#test2-produce-to-one-broker-one-partition-requiredacks0-100-byte-messages). I just wanted to see, if the library is in the same range of numbers or if we're totally behind.

I don't think that we need a request queue. Here's my proposal: We need a class `Producer` which will decide to which of the topic partitions a message should be produced (using some kind of _partitioner_ implementation, m.b. using a traits structure) and then queues the messages according to the topic partition. I'm thinking about a class `ClientManager` which holds metadata about the topic partitions as well as connections to each broker. It "knows" the leading broker for each partition. The `Producer` has one `ClientManager` object to get the `Client` object for the corresponding broker. It creates a `ProduceRequest` for each broker, including all messages for the topic partitions that the broker is currently marked as leader. So there will always be one request to one broker at the same time. If it is finished and we still have messages (or m.b. new messages in the mean time) for the broker, than the next request will be triggered.

The chat example from boost creates a separate thread, which is running all the IO work. I wanted to avoid doing any thread related stuff, as ideally all can run in a single thread. But maybe such a `Producer` requires the use of a separate thread. Anyway, the example doesn't distinguish between messages and requests. It just has messages. Taking the above approach to the boost example would mean that we still queue messages but sending all of them, currently available in the queue, as _bulk_ to the server.

Naming the `Client` to `Connection` shouldn't be a problem. Personally, I would have created a new class called `ClientManager` and keep the current `Client` class as it is, but in the end it doesn't matter. Btw. the library of @skarlsson calls the connection object `lowlevel_client`. 

I used the CRTP pattern for the `Request` as I wanted to avoid having virtual function calls. A request queue could be implemented without any change to the current `Client` implementation -- as long as you send the same kind of requests (e.g. only `ProduceRequests`) -- using a template class. But as stated above, I don't think we need one.

**Comment by DEvil0000** [comment]
>I used required_acks=0 to have nearly the same test setup as librdkafka

I am aware of this ;)
>I don't think that we need a request queue.
....
>It creates a ProduceRequest for each broker, including all messages for the topic partitions that the broker is currently marked as leader. So there will always be one request to one broker at the same time. If it is finished and we still have messages (or m.b. new messages in the mean time) for the broker, than the next request will be triggered.

This is true as long as you are using your `Client` only for the `Producer` - when you use a Client for producing and consuming (in a `Producer` and `Consumer` class sharing the same `Client`) you will need something like a request queue on the `Client` - right?
>I'm thinking about a class ClientManager ....

I think basically the same about the implementation but I think the names `Client` and `ClientManager` are confusing.
>I used the CRTP pattern for the Request as I wanted to avoid having virtual function calls. A request queue could be implemented without any change to the current Client implementation -- as long as you send the same kind of requests (e.g. only ProduceRequests) -- using a template class. But as stated above, I don't think we need one.

But I plan to send different `Requests` to a `Client`. In a program you can have multiple `Producers` and `Consumers` using the same (`"client"`) / using the same or multiple shared/separate `Clients`(`"connections"`). It would make perfect sense to share one `"client"` with one or more `"connections"` - right?

about threads:
at the moment I would not care to much about threads. It should run with one but performance wise it is important to use more later.
e.g. one (or two) thread(s) per socket. (maybe one for read and one for write - not sure about asio and/or socket details here). And some timers/deadlines may need their own thread, too.

**Comment by danieljoos** [comment]
I'm fully aware of dynamic vs. static polymorphism and of course, if you want to have a generic request queue, you might also need dynamic polymorphism using a base-request class having virtual functions.

But I don't want to queue on request level. Also the library of @skarlsson does not queue on that level. Looking at the `lowlevel_producer` of the library (see https://github.com/bitbouncer/csi-kafka/blob/master/csi_kafka/lowlevel_producer.cpp#L117  as well as the definition of `tx_item` here https://github.com/bitbouncer/csi-kafka/blob/master/csi_kafka/lowlevel_producer.h#L48) it queues only messages (plus callback) and adds as many of them as possible to a new request (of course having a limit per request) (the request is created here https://github.com/bitbouncer/csi-kafka/blob/master/csi_kafka/lowlevel_client.cpp#L259).

And this is exactly the approach I want to take for the producer/consumer implementation of the _libkafka-asio_ library.

Regarding threads: The whole approach of Boost Asio is to schedule requests/operations rather than to wait/block the thread. Threading is often done on `io_service` level (so you can have multiple threads per `io_service` object or multiple `io_service` objects, each running a separate worker thread). I don't want to implement any thread pool etc. in the library. This should be up to the client code. Adding some mutexes here and there should be fine, but I don't want the library to "dictate" a threading model.

**Comment by DEvil0000** [comment]
Take a look at the `lowlevel_client`::`perform async` method. It just binds it to call the `perform` method. And this method is queueing the requests if the socket is blocked for a action ;)

I totally agree on threads. I am just not sure if it should be "dictated" for better general performance. There is no disadvantage of creating more threads beside a longer init times. Maybe there should be a default threading/io_service model but configurable or exchangeable.

**Comment by danieljoos** [comment]
Ok, the `lowlevel_client` queues the __serialized__ request plus the callback. This would be one approach, I could live with as well. And it doesn't require any change to the current `Request` class.

**Comment by DEvil0000** [comment]
I was actually not thinking too much about serialized/not serialized. But doing it on serialized request level solves the template problem and is better performance wise. Perfect, thanks for discussing this.

Btw: why are you using mutable classes instead of just setters in the real classes and const methods on the getters.

**Comment by danieljoos** [comment]
Just to summarize the action items here:

1. In order to close this particular issue, queueing of serialized requests needs to be added to the current `Client` implementation.
2. Separate issue/enhancement for renaming `Client` to `Connection`
3. Separate issue/enhancement for creating the `Producer` implementation as discussed

Ok with that?

The mutable response classes exist for more esthetic reasons. From a functional perspective they are no longer required since the `Client::Handler<T>::Type` already enforced a `const` response parameter for the callback functions. But the current implementation is also not wrong! If you really feel bad about it, I would ask you to open another issue where we can discuss this separately and I can try to explain the reasons, why I chose to do it this way.

**Comment by DEvil0000** [comment]
sounds good.
merge request out for part 2. the renaming of the class

**Comment by DEvil0000** [comment]
I am back on:
I think it is not possible to queue the requests with the current template architecture or at least a bad idea.

We need to queue the request data and the callback/handler - right?
And the handler is again depending on templates. To be more precise the callback method parameter is different for each response class.
And as far as I know you can not store a function/method pointer without specifying the type including return and all parameter types.
Do you see a solution for this?

**Comment by skarlsson** [comment]
I'm on vacation so I'm not active on this at all for two more weeks, but I read the posts... 

>And as far as I know you can not store a function/method pointer without specifying the type including >return and all parameter types.

If I understand you you can use a two step thing as in I do in the perform code - just store some kind of "context", (ie the raw receive buffer)  and do the decoding in the callback. The you get generic receive call and can decode and make the user callback with whatever signature you want.

And to comment an older question on the same thread. You actually can gain a lot of performance (per one thread) by assuming you only have one thread in relevant parts of the code. This is the path taken by node-js. The disadvantage is that you cannot scale with number of cores without running several instances of your executable. I've chosen this path in csi-kafka.

As another comment on performance - We use avro, in some cases hardcoded avro (avrogencpp) and in other generic-datum (or whatever that is called). Performance wise we spend most of the time in this code not in kafka client code

**Comment by DEvil0000** [comment]
@skarlsson you can do it like this because you can store it in your `basic_call_context`. You can store the callback because it has a common base without template argument forcing it to a subtype.

**Comment by danieljoos** [comment]
You can use a `boost::function` type for this. The type must take 2 parameters: 1) the error code and 2) the "bytes transferred".
See https://github.com/danieljoos/libkafka-asio/blob/master/lib/libkafka_asio/impl/connection.h#L169. I would just store the bound handler and not create it "on the fly" as it is done now.

So the function object type could look like this:
```cpp
typedef boost::function<void(const Connection::ErrorCodeType& error, size_t bytes_transferred)> WriteCallbackType
```

And for the write queue, you would then need to store a structure like this:
```cpp
struct WriteQueueItem
{
  Bytes data;
  WriteCallbackType write_callback;
}
```

When adding items to the queue, you simply create the callback function object using `boost::bind` as shown in the link above.

I guess this is also what @skarlsson meant.

**Comment by DEvil0000** [comment]
I totally understand this but I don't know how you want to apply this on our template based types.
The handler we need to call at some point (and store until then) is of type:
`const typename Connection::Handler<TRequest>::Type& handler`
No matter if we store or pass it we need to take the template type.
```
template<typename TRequest>
typedef boost::function<void(const Connection::ErrorCodeType& error, size_t bytes_transferred, const typename Connection::Handler<TRequest>::Type& handler)> WriteCallbackType
```
```
template<typename TRequest>
struct WriteQueueItem
{
  Bytes data;
  WriteCallbackType<TRequest> write_callback;
}
```
```
std::queue<TRequest> queue; //But here we don't have the template information. 
```
Maybe I don't get it but I still think it is just not possible with CRTP pattern.

**Comment by danieljoos** [comment]
Using the type definition, I just posted should solve this.
You can re-use the existing `HandleAsyncRequestWrite<TRequest>` handler function.
Something like this:

```cpp
// This code could be inserted around line 165 of impl/connection.h
WriteQueueItem tx_item;
tx_item.data = buffer;  // Store the serialized request, maybe we don't even need this, as we can also bind the buffer itself to the write handler
tx_item.write_callback = 
  boost::bind(&Connection::HandleAsyncRequestWrite<TRequest>, this, 
                     boost::asio::placeholders::error,
                     boost::asio::placeholders::bytes_transferred,
                     buffer,
                     state_,
                     handler,
                     response_expected));
tx_queue.push_back(tx_item);
```

The queue type could look like this:
```cpp
typedef std::deque<WriteQueueItem> WriteQueueType;
```

The actual handler (specified by the 'user') is bound to the write handler function object. We hand it over till the point were we schedule the call to it (e.g. in line 379 of `impl/connection.h`), which will be a templated function again (`template<TRequest> void Connection::HandleAsyncResponseRead` in this case).

**Comment by DEvil0000** [comment]
Somehow you miss the point - I think I am not able to explain it better.
You will see what I mean when you try to write and compile it.
I pushed my attempt to github so you can take a look and try to solve it ;)

**Comment by danieljoos** [comment]
Added a new branch `feature-connection-queue` (https://github.com/danieljoos/libkafka-asio/tree/feature-connection-queue). There are some pitfalls regarding the error handling, which need to be addressed, but the basic queueing of requests should already work.

**Comment by DEvil0000** [comment]
OK thanks, this works. I was trying nearly the same thing but I misunderstood the boost::bind thing.
I never used this boost asio & bind before and the docs are pretty basic. ;)

You used the CRTP to save the overhead calling virtual functions - right?
I think wrapping every call up with a boost::bind is more overhead - correct?

**Comment by danieljoos** [comment]
That has nothing to do with the CRTP of the `Request` class. You would have to bind the handler (as well as some other variables) anyway.

Boost Asio does create at least one `boost::function` object behind the scenes as well. `bind` is pretty fast. It takes most of the time to copy the arguments. Internally it just stores a function pointer. It heavily relies on templates and compiler optimization. `boost::function` internally uses a virtual function call (if I'm not mistaken), so the overhead to a _plain_ virtual function is not too much (it does some exception handling and checks).

I'm not willing to change the CRTP of the `Request` class as this just doesn't help us here anyway! A write/read queue in the `Connection` class can be implemented without any change to that class. The code I posted in the `feature-connection-queue` branch of course is not optimized at all. It misses error handling as well. Also the queue needs to be protected by some locking mechanism as it introduces a possible race condition to the `Connection` class (e.g. if all ASIO related work is done in a separate worker thread). I guess this takes way more time than binding the functions. ;-)

**Comment by danieljoos** [comment]
As stated in #9, a better approach is to use the `io_service::post` instead of an exclusive locking. It already provides thread-safety.

Also inserting the serialized request must be wrapped that way.

**Comment by danieljoos** [comment]
I tried to visualize the flow inside the `Connection` class in the following diagram:
https://gist.github.com/danieljoos/9eefaa8184e741fd7514#file-connectionclassflow-svg

I guess we need to make the design decision, whether we want to use `strand` objects or not. I had a look at the implementation of `strand` and it does use `mutex`es as well, so there should be no overhead compared to directly locking a `mutex`.

We should also decide, if we want to close a connection on error (or on specific errors?).
Error paths are marked as red arrows in the above diagram (corresponds to "if error, then").

**Comment by DEvil0000** [comment]
>I tried to visualize the flow inside the Connection class in the following diagram

You missed a link from `HandleAsyncRequestWrite` -> `SendNextRequest` in case of no read. 
>The diagram shows a flow, as it should be, not as it is today. E.g. the DoSendAsyncRequest function (or whatever it get's called later on) does not yet exist.

The names with `Do` are a bit confusing - I believe the methods have more understandable names now.
`DoAsyncRequest` => `SerializeAndEnqueue`
`DoSendAsyncRequest` = `SendNextRequest`
how about using `doxygen` & `graphwiz` (or how it is called) to generate the diagram?
>I guess we need to make the design decision, whether we want to use strand objects or not. I had a look at the implementation of strand and it does use mutexes as well, so there should be no overhead compared to directly locking a mutex.

If you directly call mutex you can do it for a part of the method - strand is always locking for the whole method call. This is why I used a mutex ;)
>We should also decide, if we want to close a connection on error (or on specific errors?).

I feel like we might see some temporary network failures but after some retries I would say it is likely that the connection is gone for a while and we should close the connection.
>If we do not use strand objects, everything below the yellow dashed line is considered to run in the same thread.

Needed design decision:
It makes perfect sense to do serialisation and de-serialisation potentially multi threaded.
And as far as I understand the asio socket implementation it is perfectly valid to read & write at the same time from the same socket. So I would also like to spilt this a bit more and make it at least possible to run it in different threads.


Needed design decision:
At the moment we call error handler and queue the request on `disconnected && no_auto_connect`. I think we should only call the handler and return without queueing in this case.

**Comment by danieljoos** [comment]
> You missed a link from HandleAsyncRequestWrite -> SendNextRequest in case of no read.

Corrected that one.

> The names with Do are a bit confusing - I believe the methods have more understandable names now.
> DoAsyncRequest => SerializeAndEnqueue
> DoSendAsyncRequest = SendNextRequest
> how about using doxygen & graphwiz (or how it is called) to generate the diagram?

Name it as you wish. I just wanted to extract the part regarding the (auto-)connection and request de-queuing into a separate function.

> If you directly call mutex you can do it for a part of the method - strand is always locking for the whole method call. This is why I used a mutex ;)

I guess it doesn't really matter. I would like to try using a `strand` object as it seems to be _closer_ to the way, Boost Asio works.

> And as far as I understand the asio socket implementation it is perfectly valid to read & write at the same time from the same socket. So I would also like to spilt this a bit more and make it at least possible to run it in different threads.

Full ack. A _read queue_ makes perfect sense. This might be a bigger change (also regarding the `ConnectionState`). Therefore I started implementing a write queue first.

> At the moment we call error handler and queue the request on disconnected && no_auto_connect. > I think we should only call the handler and return without queueing in this case.

Ok, seeing that as well. This could be easily done by adding an additional `if` inside the `DoAsyncRequest`, or whatever you call it -- `SerializeAndEnqueue`... ;-)

**Comment by skarlsson** [comment]
>And as far as I understand the asio socket implementation it is perfectly
valid to read & write at the same time from the same socket

you can have one read and one write op running from the same thread at once
>
>

**Comment by DEvil0000** [comment]
>I guess it doesn't really matter. I would like to try using a strand object as it seems to be closer to the way, Boost Asio works.

It depends on the content of your methods. Every instruction unnecessarily inside a mutexed/locked scope slows down the execution.
But personally I prefer a mutex because I think it is more readable. With strand you loose the context why you need to lock it. For example you mutex is called write_queue_mtx because it protects the queue. And you lock with strand where you call the method - you might overlook the strand when you introduce a new call to the same method.

However - performance is not that important to me at the moment. If I can get more then 10k Messages out in a second (with response) I am happy.

**Comment by danieljoos** [comment]
Maybe let's first focus on an implementation that assumes that only a single thread is running the `io_service::run`! It is easy to implement and from a performance perspective, it already solves your requirements @DEvil0000 (see above measurements). I also fear that the possible performance improvement, you get when doing the serialization in multiple threads, is not worth locking at least 2 queues (read/write).

Here is a version of the diagram using the _graphviz_ language: https://gist.github.com/danieljoos/b0970fd265511a37fb2c#file-connectionclassflow-dot .
It covers a write and read queue. It assumes that all IO work is done within a single thread.
You can use http://www.webgraphviz.com/ for rendering it in the browser (unfortunately github doesn't provide such a preview).

**Comment by DEvil0000** [comment]
There should be an error path from `resolve` for `next broker`.

`HandleAsyncResponseSizeRead` should also have an error path.

What is the difference between `HandleAsyncConnect` and `HandleAsyncAutoConnect`? Do we need a error path there?

I think `Post Error Handler` on the right side should have the same connections as on the left side - but it may handle the errors slightly different. It should point to `NextRequest` not `NextResponse`. (There can only be one response per request)

The `auto connect` case from the right side looks wrong. If there is no connection any more on receiving a response we will most likely not get the expected response any more. In this case we should discard all pending responses and call the error handler for them. Then we may proceed with sending the next requests not response.

like this:
```
digraph G {
  node [shape=box]

  subgraph write_graph {
    AsyncRequest -> Serialize [style=dashed arrowhead=vee]
    Serialize -> EnqueueRequest [weight=100]
    EnqueueRequest -> NextRequest [weight=100]
    connectedw [label="connected?" shape="diamond"]
    autoconnectw [label="auto connect?" shape="diamond"]
    connectedw -> autoconnectw [weight=100 label="No"]
    NextRequest -> connectedw [weight=100]
    connectedw -> SendRequest [weight=100 label="Yes"]
    SendRequest -> HandleAsyncWriteRequest [weight=100 style=dashed arrowhead=vee]
    HandleAsyncWriteRequest -> NextRequest [weight=100]
    errorhandlerw [label="Post Error Handler"]
    HandleAsyncWriteRequest -> errorhandlerw [weight=100 color=red]
    errorhandlerw -> NextRequest [weight=100]
    autoconnectw -> errorhandlerw [weight=100 label="No"]
  }

  subgraph connect_graph {
    "is connecting?" [shape="diamond"]
    "is connecting?" -> AutoConnect [weight=100 label="No"]
    "is connecting?" -> EnqueueConnectionHandler [weight=100 label="Yes"]
    AutoConnect -> AsyncConnect [weight=100]
    AsyncConnect -> HandleAsyncResolve [weight=500 style=dashed arrowhead=vee]
    HandleAsyncResolve -> HandleAsyncConnect [weight=100 style=dashed arrowhead=vee]
    HandleAsyncConnect -> HandleAsyncAutoConnect [weight=100 style=dashed arrowhead=vee]
    HandleAsyncResolve -> AutoConnect [weight=100 label="next broker" color=red]
    HandleAsyncConnect -> AutoConnect [weight=100 label="next broker" color=red]
    HandleAsyncAutoConnect -> AutoConnect [weight=20 label="next broker" color=red]
  }

  subgraph read_graph {
    EnqueueResponse -> NextResponse [weight=100]
    connectedr [label="connected?" shape="diamond"]
    connectedr -> errorhandlerr [label="No"]
    NextResponse -> connectedr [weight=100]
    connectedr -> ReceiveResponse [weight=100 label="Yes"]
    ReceiveResponse -> HandleAsyncResponseSizeRead [weight=100 style=dashed arrowhead=vee]
    HandleAsyncResponseSizeRead -> HandleAsyncResponseRead [weight=100 style=dashed arrowhead=vee]
    HandleAsyncResponseRead -> NextResponse
    errorhandlerr [label="Post Error Handler"]
    HandleAsyncResponseSizeRead -> errorhandlerr [color=red]
    HandleAsyncResponseRead -> errorhandlerr [color=red]
    errorhandlerr -> NextRequest
  }

  autoconnectw -> "is connecting?" [label="Yes"]

  HandleAsyncAutoConnect -> SendRequest
  HandleAsyncWriteRequest -> EnqueueResponse

  { rank=same; EnqueueRequest; EnqueueResponse }
  { rank=same; connectedw; connectedr }
  { rank=same; SendRequest; ReceiveResponse }
  { rank=same; NextRequest; NextResponse }
  { rank=same; HandleAsyncWriteRequest; HandleAsyncResponseSizeRead}
  { rank=same; NextRequest; errorhandlerw}
  { rank=same; NextResponse; errorhandlerr }
  { rank=same; connectedw; autoconnectw }
}
```

**Comment by danieljoos** [comment]
For the _connection_ part of the flow, I didn't draw all error paths. This part already works fine, anyway. 

See the point with _auto connect_ for responses as well -- we don't need that.

I wouldn't discard all pending responses on every possible error. Maybe only on the connection related ones?

**Comment by DEvil0000** [comment]
>I wouldn't discard all pending responses on every possible error. Maybe only on the connection related ones?

True, sorry this was what I meant.
>In case we don't need an auto connect for responses, we can also get rid of the EnqueueConnectionHandler and is connecting? part, as we can only reach that part from the write side.

True

**Comment by DEvil0000** [comment]
Do we even need more than one broker ip/host configured for a `Connection`?
I would suggest a `Client` taking a set of hosts and establishing one `Connection` per host.

**Comment by danieljoos** [comment]
Sound reasonable! Let's do it that way.

**Comment by DEvil0000** [comment]
What do you think about this as a basis Client for simpleProducer & Consumer: https://github.com/DEvil0000/libkafka-asio/commits/feature-connection-queue%23client

**Comment by danieljoos** [comment]
The implementation of the read/write queues is nearly done. See branch `feature-connection-queue` With commit 94bfe2911661c915d4f298c947b835f2df0bd279 I switched the implementation of the `Connection` to a Asio service based one. This has quite some advantages, e.g. that stupid `kStateDestroyed` is no longer required.

The `auto-connect` feature is missing by now. Also the examples + docs need to be adapted before this can be merged to master.

**Comment by danieljoos** [comment]
Read/Write queue feature has been added with #14. Therefore closing this issue.
I would like to address the consumer/producer implementation in a separate enhancement/issue.
